### ISSUE TITLE
com.google.android.exoplayer2.source.UnrecognizedInputFormatException on some videos

### ISSUE THREAD

**Issue by altrr2** [ponnamkarthik/ext_video_player#10]
HI. Most videos I tried work fine, but some appear to have a problem (tried on both Pixel 3a XL Android 11 beta with Google Play and Huawei p40 lite E Android 9.0 without Google Play - same error):

https://www.youtube.com/watch?v=3Aa00dDOv1I

/ExoPlayerImpl(23222): Init 5b03d35 [ExoPlayerLib/2.9.6] [HWART-H, ART-L29, HUAWEI, 28]
E/ExoPlayerImplInternal(23222): Source error.
E/ExoPlayerImplInternal(23222): com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor) could read the stream.
E/ExoPlayerImplInternal(23222): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:973)
E/ExoPlayerImplInternal(23222): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:891)
E/ExoPlayerImplInternal(23222): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(23222): 	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
E/ExoPlayerImplInternal(23222): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)

**Comment by gkathir15** [comment]
a workaround is posted for player issues, 
This could work https://github.com/ponnamkarthik/ext_video_player/issues/6#issuecomment-726814967
