### ISSUE TITLE
RTMP is not working on web

### ISSUE THREAD

**Issue by Alijaaan** [ponnamkarthik/ext_video_player#24]
Hi,

I tested the example with default and my rtmp source but it seems it's not working on web :
Error : 
PlatformException(MEDIA_ERR_SRC_NOT_SUPPORTED, MEDIA_ELEMENT_ERROR: Format error, The video has been found to be unsuitable (missing or in a format not supported by your browser)., null)

Am I doing something wrong?

**Comment by Alijaaan** [comment]
Is there any answer?

**Comment by ponnamkarthik** [comment]
Not implemented

**Comment by Alijaaan** [comment]
> Not implemented for web

Thanks for your answer dear ponnamkarthik
Is there any way to implement this?
Any lead or guide?

**Comment by ponnamkarthik** [comment]
RTMP is only supported on android
