### ISSUE TITLE
Some Issues with Youtube Videos Playing

### ISSUE THREAD

**Issue by tanveer1302** [ponnamkarthik/ext_video_player#4]
Hi,

First of all, great work. Had been looking for something like this for a very long time. I have few requests for features and some issues that I am encountering while trying to play Youtube videos with this. So, will divide this post in two parts, requests and issues.

**Requests:**
1) In the readme file can you add some properties that are with this package and we can play with. Currently I am unable to find anything close to it.
2) Can you add full screen view option in the videos.
3) Can you add some identifier to the seek bar, like a bubble over the slider of seek bar.

**Issues encountered:**
1) Youtube videos don't have any volume. Tried on android simulator and real device as well, but volume doesn't seem working at all.
2) Very limited youtube videos are playing. Some videos that I tried and didn't worked are
- https://www.youtube.com/watch?v=LKZcT-syexg
- https://www.youtube.com/watch?v=UJWk_KNbDHo
- https://www.youtube.com/watch?v=zc8hbSM1zVo

Looking forward to your response, mate.

Once again, keep up the good work.

**Comment by rahulairsky** [comment]
Hi , Same issue is here. Youtube videos are playing but there are no sound coming.

**Comment by rahulairsky** [comment]
D/        ( 7494): HostConnection::get() New Host Connection established 0x93277740, tid 7516
D/        ( 7494): HostConnection::get() New Host Connection established 0x82d2a540, tid 7640
I/cr_LibraryLoader( 7494): Using linker: org.chromium.base.library_loader.ModernLinker
E/BluetoothAdapter( 7494): Bluetooth binder is null
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
D/EGL_emulation( 7494): eglMakeCurrent: 0x932b5920: ver 3 0 (tinfo 0x911fe660)
D/        ( 7494): HostConnection::get() New Host Connection established 0x93318640, tid 7675
D/EGL_emulation( 7494): eglCreateContext: 0xa6e53380: maj 3 min 0 rcv 3
D/EGL_emulation( 7494): eglMakeCurrent: 0xa6e53380: ver 3 0 (tinfo 0x8512ddd0)
I/VideoCapabilities( 7494): Unsupported profile 4 for video/mp4v-es
W/cr_MediaCodecUtil( 7494): HW encoder for video/avc is not available on this device.
D/EGL_emulation( 7494): eglCreateContext: 0x933a1740: maj 3 min 0 rcv 3
D/EGL_emulation( 7494): eglMakeCurrent: 0x933a1740: ver 3 0 (tinfo 0x8512ddd0)
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
D/        ( 7494): HostConnection::get() New Host Connection established 0x93318440, tid 7665
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
I/zygote  ( 7494): NativeAlloc concurrent copying GC freed 17569(1226KB) AllocSpace objects, 28(964KB) LOS objects, 49% free, 3MB/7MB, paused 501us total 124.167ms
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread
W/zygote  ( 7494): Attempt to remove non-JNI local reference, dumping thread

**Comment by tanveer1302** [comment]
> Hi , Same issue is here. Youtube videos are playing but there are no sound coming.

@rahulairsky did any of these video links work for you?

    https://www.youtube.com/watch?v=LKZcT-syexg
    https://www.youtube.com/watch?v=UJWk_KNbDHo
    https://www.youtube.com/watch?v=zc8hbSM1zVo

**Comment by rahulairsky** [comment]
No, these are not playing

**Comment by tanveer1302** [comment]
did anyone found a solution to it?????

**Comment by ponnamkarthik** [comment]
Youtube audio issue fixed check version `0.0.3`
