### ISSUE TITLE
Youtube video voice not working 

### ISSUE THREAD

**Issue by 1morecode** [ponnamkarthik/ext_video_player#5]
Everything is good, but YouTube video voice is not working and please try to implement full screen toggle buttons.

**Comment by tanveer1302** [comment]
did you find any solution to it?

**Comment by danielmessi13** [comment]
Same issue is here

**Comment by ponnamkarthik** [comment]
Can you send me the url you used to play

**Comment by danielmessi13** [comment]
> Can you send me the url you used to play

I copied the example that is in the repository, this is the url:
https://www.youtube.com/watch?v=YFCSODyFxbE

**Comment by tanveer1302** [comment]
> Can you send me the url you used to play

and as i mentioned in other post, these videos are not playing at all. Any idea what the issue can be?


    https://www.youtube.com/watch?v=LKZcT-syexg
    https://www.youtube.com/watch?v=UJWk_KNbDHo
    https://www.youtube.com/watch?v=zc8hbSM1zVo

**Comment by ponnamkarthik** [comment]
Fixed in `0.0.3`
