### ISSUE TITLE
All Youtube Videos not working

### ISSUE THREAD

**Issue by tanveer1302** [ponnamkarthik/ext_video_player#6]
Very limited youtube videos are playing. Some videos that I tried and didn't worked are

    https://www.youtube.com/watch?v=LKZcT-syexg
    https://www.youtube.com/watch?v=UJWk_KNbDHo
    https://www.youtube.com/watch?v=zc8hbSM1zVo

**Comment by Joseph-Nathan** [comment]
same issue with me

**Comment by Joseph-Nathan** [comment]
man this plug-in ,is vary great 
it is not have issue in have a flage_secure or in different devices like webview 
please solve this issue

**Comment by ponnamkarthik** [comment]
@tanveer1302 @Joseph-Nathan 

This plugin parses download link from youtube download and some times it youtube wont allow download link for some videos

**Comment by faslurrajah** [comment]
Why some videos are not playing? It's throwing an exception 
[ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException, null, null)

**Comment by gkathir15** [comment]
I have a workaround for this issue,
on _controller.value.onError 
I would use the [flutter youtubeplayer](https://github.com/sarbagyastha/youtube_player_flutter)
Since the plugin uses web view, un-playable videos will be played.

**Comment by qhu91it** [comment]
For better customize I think we can use [youtube_explode_dart](https://github.com/Hexer10/youtube_explode_dart) lib to get video stream link and can be use with ext_video_player or other video player.

Something like that
```
var yt = YoutubeExplode();
var streamManifest = await yt.videos.streamsClient.getManifest(videoId);
videoUrl = streamManifest.muxed.first.url.toString();
```

**Comment by wackyapps** [comment]
> For better customize I think we can use lib [youtube_explode_dart](https://github.com/Hexer10/youtube_explode_dart) to get video stream link and can be use with ext_video_player or other video player.
> 
> Something like that
> 
> ```
> var yt = YoutubeExplode();
> var streamManifest = await yt.videos.streamsClient.getManifest(videoId);
> videoUrl = streamManifest.muxed.first.url.toString();
> ```

Yes, I have been using [youtube_explode_dart](https://github.com/Hexer10/youtube_explode_dart) and it works for all videos from YouTube. This package parse streams from ajax call to YouTube.com and allow you to play in any player

**Comment by ponnamkarthik** [comment]
migrated to youtube_explode_dart for getting youtube url `0.0.5`

**Comment by juniorkibirige** [comment]
Null safety implementation 

`Because every version of ext_video_player depends on http ^0.12.2 and google_fonts 2.0.0 depends on http ^0.13.0, ext_video_player is incompatible with google_fonts 2.0.0.

And because no versions of google_fonts match >2.0.0 <3.0.0, ext_video_player is incompatible with google_fonts ^2.0.0.

So, because mci depends on both google_fonts ^2.0.0 and ext_video_player ^0.0.6, version solving failed.
pub get failed (1; So, because mci depends on both google_fonts ^2.0.0 and ext_video_player ^0.0.6, version solving failed.)
exit code 1`
Any solution
