### ISSUE TITLE
provide youtube live video support also and video quality options , speedo meter(playback rate) 

### ISSUE THREAD

**Issue by shailendra-rajpoot** [ponnamkarthik/ext_video_player#9]
provide youtube live video support also and video quality options , speedo meter(playback rate).
i want this feature plz tell me  how to do this from my side or wait for update from your side.

**Comment by workerbee22** [comment]
Second this. How do you pick the video and audio streams? Would like to have at least 'broad' selection of quality from YouTube ie. 480p, 720p, 2160p etc. if they are available.
